CAT = [('A01PR', 'A-Progettazione'),
    ('A02DL', 'A-Direzione lavori'),
    ('A03CT', 'A-Catasto'),
    ('A04PE', 'A-Perizie'),
    ('A05AN', 'A-Anticipazioni'),
    ('A00', 'A-Varie'),
    ('X', 'Altro'),
    ('P05CO', 'P-Collaboratori'),
    ('P01AU', 'P-Autoveicoli'),
    ('P02AT', 'P-Attrezzature'),
    ('P14SE', 'P-Servizi'),
    ('P13FO', 'P-Formazione'),
    ('P03CA', 'P-Cancelleria'),
    ('P04TE', 'P-Telefoni'),
    ('P11ER', 'P-Erogazioni'),
    ('P12AF', 'P-Affitti'),
    ('P07AS', 'P-Assicurazioni'),
    ('P09PR', 'P-Previdenza'),
    ('P10TA', 'P-Tasse'),
    ('P06RE', 'P-Restituzioni'),
    ('P08DI', 'P-Dividendi'),
    ('P00', 'P-Varie'),
    ]
