from django.utils.translation import gettext as _

CAT = [('A01PR', 'A-'+_('Architectural design')),
    ('A02DL', 'A-'+_('Construction supervision')),
    ('A03CT', 'A-'+_('Land registry')),
    ('A04PE', 'A-'+_('Expertise')),
    ('A05AN', 'A-'+_('Anticipazioni')),
    ('A00', 'A-'+_('Various')),
    ('X', 'Altro'),
    ('P05CO', 'P-'+_('Staff')),
    ('P01AU', 'P-'+_('Fleet')),
    ('P02AT', 'P-'+_('Equipment')),
    ('P14SE', 'P-'+_('Services')),
    ('P13FO', 'P-'+_('Training')),
    ('P03CA', 'P-'+_('Office products')),
    ('P04TE', 'P-'+_('Telecom')),
    ('P11ER', 'P-'+_('Supplies')),
    ('P12AF', 'P-'+_('Rentals')),
    ('P07AS', 'P-'+_('Assurances')),
    ('P09PR', 'P-'+_('Social security')),
    ('P10TA', 'P-'+_('Taxes')),
    ('P06RE', 'P-'+_('Refunds')),
    ('P08DI', 'P-'+_('Dividends')),
    ('P00', 'P-'+_('Various')),
    ]
