# Generated by Django 3.1.2 on 2020-11-18 17:23

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_squashed_0010_csvinvoice_failed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvinvoice',
            options={'ordering': ('-date',), 'verbose_name': 'CSV/XML file', 'verbose_name_plural': 'CSV/XML files'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-date',), 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterField(
            model_name='csvinvoice',
            name='csv',
            field=models.FileField(max_length=200, upload_to='uploads/invoices/csv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xml'])], verbose_name='CSV / XML file'),
        ),
        migrations.AlterField(
            model_name='csvinvoice',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='active',
            field=models.BooleanField(default=False, help_text='Active if checked, passive if not', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Taxable'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='category',
            field=models.CharField(choices=[('A01PR', 'A-Progettazione'), ('A02DL', 'A-Direzione lavori'), ('A03CT', 'A-Catasto'), ('A04PE', 'A-Perizie'), ('A05AN', 'A-Anticipazioni'), ('A00', 'A-Varie'), ('X', 'Altro'), ('P05CO', 'P-Collaboratori'), ('P01AU', 'P-Autoveicoli'), ('P02AT', 'P-Attrezzature'), ('P14SE', 'P-Servizi'), ('P13FO', 'P-Formazione'), ('P03CA', 'P-Cancelleria'), ('P04TE', 'P-Telefoni'), ('P11ER', 'P-Erogazioni'), ('P12AF', 'P-Affitti'), ('P07AS', 'P-Assicurazioni'), ('P09PR', 'P-Previdenza'), ('P10TA', 'P-Tasse'), ('P06RE', 'P-Restituzioni'), ('P08DI', 'P-Dividendi'), ('P00', 'P-Varie')], default='X', help_text="'A' for active and 'P' for passive.\n            ", max_length=5, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.CharField(max_length=100, verbose_name='Client/Supplier'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='descr',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Payed'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='security',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Social security'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='VAT'),
        ),
    ]
