# Generated by Django 3.0.4 on 2020-04-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Imponibile'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='security',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Contributo previdenziale'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='IVA'),
        ),
    ]
