# Generated by Django 3.0.4 on 2020-04-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20200404_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='active',
            field=models.BooleanField(default=False, help_text='Se selezionato è attiva, altrimenti è passiva', verbose_name='Attiva'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='security',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Contributo previdenziale'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='IVA'),
        ),
    ]
