# Generated by Django 3.0.10 on 2020-09-27 20:57

from django.db import migrations, models
import django.utils.timezone
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20200405_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('csv', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='File CSV')),
            ],
            options={
                'verbose_name': 'File CSV',
                'verbose_name_plural': 'File CSV',
                'ordering': ('-date',),
            },
        ),
        migrations.AlterField(
            model_name='invoice',
            name='category',
            field=models.CharField(choices=[('A01PR', 'A-Progettazione'), ('A02DL', 'A-Direzione lavori'), ('A03CT', 'A-Catasto'), ('A04PE', 'A-Perizie'), ('A05AN', 'A-Anticipazioni'), ('X', 'Altro'), ('P05CO', 'P-Collaboratori'), ('P01AU', 'P-Autoveicoli'), ('P02AT', 'P-Attrezzature'), ('P13FO', 'P-Formazione'), ('P03CA', 'P-Cancelleria'), ('P04TE', 'P-Telefoni'), ('P11ER', 'P-Erogazioni'), ('P12AF', 'P-Affitti'), ('P07AS', 'P-Assicurazioni'), ('P09PR', 'P-Previdenza'), ('P10TA', 'P-Tasse'), ('P06RE', 'P-Restituzioni'), ('P08DI', 'P-Dividendi')], default='X', help_text="'A' per le attive e 'P' per le passive.\n            ", max_length=5, verbose_name='Categoria'),
        ),
    ]
