# Generated by Django 3.0.10 on 2020-09-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20200927_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvinvoice',
            name='csv',
            field=models.FileField(max_length=200, upload_to='uploads/invoices/csv/', verbose_name='File CSV'),
        ),
    ]
