# Generated by Django 3.0.10 on 2020-10-01 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20200928_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvinvoice',
            name='csv',
            field=models.FileField(max_length=200, upload_to='uploads/invoices/csv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='File CSV'),
        ),
    ]
