# Generated by Django 3.1.2 on 2020-10-06 13:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20201003_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvinvoice',
            options={'ordering': ('-date',), 'verbose_name': 'File CSV/XML', 'verbose_name_plural': 'File CSV/XML'},
        ),
        migrations.AlterField(
            model_name='csvinvoice',
            name='created',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='csvinvoice',
            name='csv',
            field=models.FileField(max_length=200, upload_to='uploads/invoices/csv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xml'])], verbose_name='File CSV / XML'),
        ),
        migrations.AlterField(
            model_name='csvinvoice',
            name='modified',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='category',
            field=models.CharField(choices=[('A01PR', 'A-Progettazione'), ('A02DL', 'A-Direzione lavori'), ('A03CT', 'A-Catasto'), ('A04PE', 'A-Perizie'), ('A05AN', 'A-Anticipazioni'), ('A00', 'A-Varie'), ('X', 'Altro'), ('P05CO', 'P-Collaboratori'), ('P01AU', 'P-Autoveicoli'), ('P02AT', 'P-Attrezzature'), ('P14SE', 'P-Servizi'), ('P13FO', 'P-Formazione'), ('P03CA', 'P-Cancelleria'), ('P04TE', 'P-Telefoni'), ('P11ER', 'P-Erogazioni'), ('P12AF', 'P-Affitti'), ('P07AS', 'P-Assicurazioni'), ('P09PR', 'P-Previdenza'), ('P10TA', 'P-Tasse'), ('P06RE', 'P-Restituzioni'), ('P08DI', 'P-Dividendi'), ('P00', 'P-Varie')], default='X', help_text="'A' per le attive e 'P' per le passive.\n            ", max_length=5, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.date(2020, 10, 6), verbose_name='Data'),
        ),
    ]
