# Generated by Django 3.1.2 on 2020-10-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20201006_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvinvoice',
            name='failed',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
